theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.file-picker]
git-ignore = true
hidden = false
parents = true

[editor.auto-save]
focus-lost = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
space.w = ":w"
space.q = ":q"
space.b.d = ":bc"
space.b.o = ":bco"
space.f = "file_picker_in_current_directory"
space.F = "file_picker"
space.b.p = "buffer_picker"
space.e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
space.E = "no_op"
